name: seat_picker_flow
description: A simple mocked implementation of Jarek Mackow flow from dribble

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.5.0
  animated_text_kit: ^1.3.1
  rect_getter: ^0.0.1
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true